### ISSUE TITLE
thyme show panics when 1 second snapshot

### ISSUE THREAD

**Issue by xcombelle** [sourcegraph/thyme#5]
I tryed to make one second snapshot and thyme panics

here is the stacktrace 
```
xcombelle@ender ~/d/t/bin> ./thyme show -i thyme.json -w stats
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4bd9e0]

goroutine 1 [running]:
panic(0x5f69e0, 0xc8200120d0)
	/home/xcombelle/.local/go/src/runtime/panic.go:481 +0x3e6
github.com/sourcegraph/thyme.Stats.func1(0x0, 0xc8200b5608, 0x3c00069)
	/home/xcombelle/dev/thyme/src/github.com/sourcegraph/thyme/show.go:17 +0x20
github.com/sourcegraph/thyme.NewTimeline(0xc8200aa920, 0x69a658, 0xc8200aa920)
	/home/xcombelle/dev/thyme/src/github.com/sourcegraph/thyme/show.go:142 +0x3d8
github.com/sourcegraph/thyme.Stats(0xc8200aa920, 0x0, 0x0)
	/home/xcombelle/dev/thyme/src/github.com/sourcegraph/thyme/show.go:17 +0x46
main.(*ShowCmd).Execute(0x758400, 0xc8200a8cd0, 0x0, 0x5, 0x0, 0x0)
	/home/xcombelle/dev/thyme/src/github.com/sourcegraph/thyme/cmd/thyme/main.go:114 +0x59e
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc8200c4000, 0xc82000a0d0, 0x5, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/xcombelle/dev/thyme/src/github.com/jessevdk/go-flags/parser.go:314 +0xa83
github.com/jessevdk/go-flags.(*Parser).Parse(0xc8200c4000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/xcombelle/dev/thyme/src/github.com/jessevdk/go-flags/parser.go:185 +0x9b
main.main.func1(0x0, 0x0)
	/home/xcombelle/dev/thyme/src/github.com/sourcegraph/thyme/cmd/thyme/main.go:141 +0x2f
main.main()
	/home/xcombelle/dev/thyme/src/github.com/sourcegraph/thyme/cmd/thyme/main.go:148 +0x23
```

here how I called `thyme show`

```
xcombelle@ender ~/d/t/bin> watch -n 30 ./thyme track -o thyme.json
xcombelle@ender ~/d/t/bin> watch -n 1 ./thyme track -o thyme.json
```

**Comment by Gui13** [comment]
I have the same issue for 30s lapse. See #15

**Comment by Olreich** [comment]
Try pulling the latest master and doing it again, should be fixed by #45.
